#! /bin/sh
# From https://codeberg.org/Limine/limine-c-template-x86-64/src/branch/trunk/kernel/get-deps

set -e

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

clone_repo_commit() {
    if test -d "$2/.git"; then
        git -C "$2" reset --hard
        git -C "$2" clean -fd
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
        fi
    else
        if test -d "$2"; then
            echo "error: '$2' is not a Git repository" 1>&2
            exit 1
        fi
    fi
    if ! test -d "$2"; then
        git clone $1 "$2"
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
            exit 1
        fi
    fi
}

rm -f .deps-obtained

clone_repo_commit \
    https://codeberg.org/Limine/limine-protocol.git \
    limine-protocol \
    068b6481557db836e41bf644382367f8dee76d21

touch .deps-obtained

printf "\nDependencies obtained successfully.\n"
